(clear)
(open "input.txt" inputFile "r")
(open "output.txt" outputFile "w")
(open "outputNOCOMMENTS.txt" outputFile2 "w")
(load globals.clp)
(load facts.clp)
(load funct.clp)
(load rules.clp)

(reset)
(watch rules)
(watch facts)
(agenda)
(facts)
(run)
(facts)

(close outputFile)
(close outputFile2)
(close inputFile)
